import React from 'react';

interface A4FooterProps {
  pageNumber: number;
  totalPages: number;
  docketId: string;
  securityHash?: string;
  confidentialityNotice?: string;
  language?: 'ru' | 'en';
  theme?: 'reoxy' | 'micor' | 'minimal';
}

export const A4Footer: React.FC<A4FooterProps> = ({
  pageNumber,
  totalPages,
  docketId,
  confidentialityNotice,
  language = 'ru',
  theme = 'minimal'
}) => {
  const isRu = language === 'ru';
  const isReoxy = theme === 'reoxy';
  const defaultNotice = isRu
    ? 'Официальный документ. Сформирован в защищенной системе документарного учета.'
    : 'Official confidential document. Generated by authorized records ledger.';

  return (
    <footer className={`avoid-break mt-auto pt-2 flex items-center justify-between gap-4 font-mono select-none ${isReoxy ? 'text-[10px] text-[#475569]' : 'text-[9px] text-[#64748b] border-t border-[#e2e8f0] pt-4'}`}>
      <div className="min-w-0 flex-1 truncate">
        {confidentialityNotice || defaultNotice}
      </div>

      <div className="flex items-center gap-3 shrink-0 whitespace-nowrap">
        <span className="text-[#94a3b8]">
          DOC: {docketId}
        </span>
        <span className={`font-semibold text-[#0f172a] whitespace-nowrap ${isReoxy ? 'rounded-full border border-[#bae6fd] bg-[#f0f9ff] px-2 py-0.5 text-[#0284c7]' : 'border border-[#cbd5e1] px-1.5 py-0.5 bg-[#f8fafc]'}`}>
          {isRu ? `Стр. ${pageNumber} из ${totalPages}` : `Page ${pageNumber} of ${totalPages}`}
        </span>
      </div>
    </footer>
  );
};
